-- Credits are server-owned: clients never write balances or ledger entries.
alter table public.profiles add column if not exists is_trial boolean not null default true;
-- Accounts that existed before this rollout are paid/regular accounts; only
-- profiles created after the migration receive the trial default.
update public.profiles set is_trial = false;

alter table public.orders add column if not exists credits_charged numeric(18,2) not null default 0;
alter table public.orders drop constraint if exists orders_payment_method_check;
alter table public.orders add constraint orders_payment_method_check check (payment_method in ('bank_transfer', 'crypto', 'credit'));

create table if not exists public.credit_wallets (
  profile_id bigint primary key references public.profiles(id) on delete cascade,
  balance numeric(18,2) not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);
create table if not exists public.credit_ledger (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete restrict,
  amount numeric(18,2) not null check (amount <> 0),
  balance_after numeric(18,2) not null check (balance_after >= 0),
  type text not null check (type in ('trial_grant','admin_grant','admin_adjustment','order_debit','refund')),
  reference text unique,
  note text not null default '',
  created_by_profile_id bigint references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists credit_ledger_profile_created_idx on public.credit_ledger(profile_id, created_at desc);

create or replace function public.prevent_credit_ledger_mutation()
returns trigger language plpgsql security definer set search_path = pg_catalog, public as $$
begin
  raise exception 'Credit ledger entries are immutable';
end;
$$;
drop trigger if exists credit_ledger_immutable on public.credit_ledger;
create trigger credit_ledger_immutable before update or delete on public.credit_ledger
for each row execute function public.prevent_credit_ledger_mutation();

insert into public.app_settings(key, value) values
  ('credits_per_usd', '100'::jsonb),
  ('trial_credit_amount', '100'::jsonb)
on conflict (key) do nothing;

insert into public.credit_wallets(profile_id) select id from public.profiles on conflict do nothing;

create or replace function public.grant_profile_credits(target_profile_id bigint, credit_amount numeric, entry_type text, entry_note text default '', actor_profile_id bigint default null, entry_reference text default null)
returns numeric language plpgsql security definer set search_path = pg_catalog, public as $$
declare next_balance numeric;
begin
  if credit_amount = 0 then raise exception 'Credit adjustment cannot be zero'; end if;
  if entry_type not in ('trial_grant','admin_grant','admin_adjustment','refund') then raise exception 'Unsupported credit entry type'; end if;
  insert into public.credit_wallets(profile_id) values (target_profile_id) on conflict do nothing;
  select balance + credit_amount into next_balance from public.credit_wallets where profile_id = target_profile_id for update;
  if next_balance < 0 then raise exception 'Credit balance cannot become negative'; end if;
  update public.credit_wallets set balance = next_balance, updated_at = now() where profile_id = target_profile_id;
  insert into public.credit_ledger(profile_id, amount, balance_after, type, reference, note, created_by_profile_id)
  values (target_profile_id, credit_amount, next_balance, entry_type, entry_reference, coalesce(entry_note,''), actor_profile_id);
  return next_balance;
end;
$$;

create or replace function public.initialize_profile_credit_wallet()
returns trigger language plpgsql security definer set search_path = pg_catalog, public as $$
declare trial_amount numeric := 0;
begin
  insert into public.credit_wallets(profile_id) values (new.id) on conflict do nothing;
  if new.is_trial and new.role = 'client' then
    trial_amount := coalesce((select (value #>> '{}')::numeric from public.app_settings where key = 'trial_credit_amount'), 100);
    if trial_amount > 0 then
      perform public.grant_profile_credits(new.id, trial_amount, 'trial_grant', 'Welcome trial credit', null, 'trial:' || new.id::text);
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists profiles_initialize_credit_wallet on public.profiles;
create trigger profiles_initialize_credit_wallet after insert on public.profiles for each row execute function public.initialize_profile_credit_wallet();

create or replace function public.create_proxy_order(target_profile_id bigint, target_product_id bigint, requested_nodes integer, requested_days integer, requested_payment_method text)
returns bigint language plpgsql security definer set search_path = pg_catalog, public as $$
declare selected_product record; profile_row public.profiles%rowtype; new_order_id bigint; total_usd numeric; credit_cost numeric; credit_rate numeric; wallet_balance numeric;
begin
  if requested_nodes < 1 or requested_nodes > 100 then raise exception 'Node quantity must be between 1 and 100'; end if;
  if requested_days < 1 or requested_days > 365 then raise exception 'Rental days must be between 1 and 365'; end if;
  if requested_payment_method not in ('bank_transfer','crypto','credit') then raise exception 'Unsupported payment method'; end if;
  select * into profile_row from public.profiles where id = target_profile_id and status = 'active' for update;
  if not found then raise exception 'Customer account is not active'; end if;
  if profile_row.is_trial and requested_nodes > 1 then raise exception 'Trial accounts can rent only one node'; end if;
  select id,name,base_price,currency,service_type into selected_product from public.products where id = target_product_id and is_active = true for share;
  if not found or selected_product.service_type <> 'proxy' or selected_product.base_price <= 0 then raise exception 'Proxy product is unavailable'; end if;
  total_usd := selected_product.base_price * requested_nodes * requested_days;
  if selected_product.currency <> 'USD' then raise exception 'Credit checkout supports USD proxy products only'; end if;
  if profile_row.is_trial and total_usd > selected_product.base_price then raise exception 'Trial credit is limited to one node for one day'; end if;
  if requested_payment_method = 'credit' then
    credit_rate := coalesce((select (value #>> '{}')::numeric from public.app_settings where key = 'credits_per_usd'), 100);
    if credit_rate <= 0 then raise exception 'Credit conversion rate is not configured'; end if;
    credit_cost := ceil(total_usd * credit_rate * 100) / 100;
    insert into public.credit_wallets(profile_id) values (target_profile_id) on conflict do nothing;
    select balance into wallet_balance from public.credit_wallets where profile_id = target_profile_id for update;
    if wallet_balance < credit_cost then raise exception 'Insufficient credit balance'; end if;
  else credit_cost := 0; end if;
  insert into public.orders(order_group_id,profile_id,product_id,plan_id,resource_id,status,payment_method,amount,currency,unit_price,node_count,rental_days,plan_name_snapshot,resource_name_snapshot,pending_expires_at,credits_charged)
  values (gen_random_uuid(),target_profile_id,selected_product.id,null,null,'pending',requested_payment_method,total_usd,selected_product.currency,selected_product.base_price,requested_nodes,requested_days,selected_product.name,format('%s nodes',requested_nodes),now()+interval '30 minutes',credit_cost)
  returning id into new_order_id;
  if requested_payment_method = 'credit' then
    update public.credit_wallets set balance = balance - credit_cost, updated_at = now() where profile_id = target_profile_id returning balance into wallet_balance;
    insert into public.credit_ledger(profile_id,amount,balance_after,type,reference,note) values (target_profile_id,-credit_cost,wallet_balance,'order_debit','order:'||new_order_id::text,format('Proxy order #%s',new_order_id));
    perform public.transition_order(new_order_id, 'active', target_profile_id);
  end if;
  return new_order_id;
end;
$$;

alter table public.credit_wallets enable row level security;
alter table public.credit_ledger enable row level security;
revoke all on public.credit_wallets, public.credit_ledger from anon, authenticated;
revoke all on function public.grant_profile_credits(bigint,numeric,text,text,bigint,text) from public, anon, authenticated;
revoke all on function public.create_proxy_order(bigint,bigint,integer,integer,text) from public, anon, authenticated;
grant all on public.credit_wallets, public.credit_ledger to service_role;
grant execute on function public.grant_profile_credits(bigint,numeric,text,text,bigint,text) to service_role;
grant execute on function public.create_proxy_order(bigint,bigint,integer,integer,text) to service_role;
