create table public.static_residential_proxies (
  id bigint generated by default as identity primary key,
  label text,
  host text not null,
  port integer not null check (port between 1 and 65535),
  username text not null,
  password_ciphertext text not null,
  password_iv text not null,
  password_tag text not null,
  status text not null default 'available' check (status in ('available','assigned','disabled')),
  assigned_order_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(host, port, username)
);

create table public.static_residential_orders (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete restrict,
  status text not null default 'active' check (status in ('active','quota_exceeded','expired','suspended','cancelled')),
  node_count integer not null default 5 check (node_count = 5),
  quota_bytes bigint not null default 5368709120 check (quota_bytes = 5368709120),
  used_bytes bigint not null default 0 check (used_bytes >= 0),
  price_per_gb_day numeric(18,4) not null check (price_per_gb_day >= 0),
  amount numeric(18,4) not null check (amount >= 0),
  credit_cost numeric(18,4) not null check (credit_cost >= 0),
  activated_at timestamptz not null default now(),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.static_residential_proxies add constraint static_residential_proxies_order_fk foreign key (assigned_order_id) references public.static_residential_orders(id) on delete set null;

create table public.static_residential_nodes (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.static_residential_orders(id) on delete cascade,
  upstream_proxy_id bigint not null references public.static_residential_proxies(id) on delete restrict,
  public_port integer not null unique check (public_port between 10000 and 20000),
  service_name text not null unique,
  status text not null default 'active' check (status in ('active','suspended','expired','quota_exceeded')),
  next_upstream_rotation_at timestamptz not null default now() + interval '1 hour',
  last_upstream_rotation_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index static_residential_orders_profile_idx on public.static_residential_orders(profile_id, created_at desc);
create index static_residential_nodes_order_idx on public.static_residential_nodes(order_id);
create index static_residential_nodes_rotation_idx on public.static_residential_nodes(next_upstream_rotation_at) where status = 'active';
create unique index static_residential_nodes_active_upstream_idx on public.static_residential_nodes(upstream_proxy_id) where status = 'active';

insert into public.app_settings(key, value) values
  ('static_residential_price_per_gb_day', '0'::jsonb)
on conflict (key) do nothing;

-- Security-critical checkout path: the client never supplies node count, quota,
-- price, or a proxy id. Five distinct upstream proxies are locked and allocated
-- atomically together with the credit debit.
create or replace function public.create_static_residential_order(target_profile_id bigint, requested_days integer)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_row public.profiles%rowtype;
  selected_proxy_ids bigint[];
  new_order_id bigint;
  price_per_gb_day_value numeric;
  credits_per_usd_value numeric;
  total_usd numeric;
  credit_cost_value numeric;
  wallet_balance numeric;
  expiry timestamptz;
  i integer;
  allocated_port integer;
begin
  if requested_days not in (1, 3, 7, 15, 30) then
    raise exception 'Rental days must be one of: 1, 3, 7, 15, or 30';
  end if;

  select * into profile_row from public.profiles where id = target_profile_id for update;
  if not found then raise exception 'Profile not found'; end if;
  if profile_row.is_trial then raise exception 'Static residential proxy is not available for trial accounts'; end if;
  if exists (select 1 from public.static_residential_orders where profile_id = target_profile_id and status = 'active' and expires_at > now()) then
    raise exception 'Each account is limited to one active static residential order (5 nodes)';
  end if;

  select coalesce((value #>> '{}')::numeric, 0) into price_per_gb_day_value
  from public.app_settings where key = 'static_residential_price_per_gb_day';
  if coalesce(price_per_gb_day_value, 0) <= 0 then raise exception 'Static residential pricing has not been configured'; end if;
  select coalesce((value #>> '{}')::numeric, 100) into credits_per_usd_value
  from public.app_settings where key = 'credits_per_usd';
  if credits_per_usd_value <= 0 then raise exception 'Credit conversion rate is not configured'; end if;

  select array_agg(id order by id) into selected_proxy_ids from (
    select id from public.static_residential_proxies
    where status = 'available'
    order by id
    for update skip locked
    limit 5
  ) candidates;
  if coalesce(array_length(selected_proxy_ids, 1), 0) <> 5 then
    raise exception 'No capacity: five static residential proxies are required';
  end if;

  total_usd := round(price_per_gb_day_value * 5 * requested_days, 4);
  credit_cost_value := ceil(total_usd * credits_per_usd_value * 100) / 100;
  insert into public.credit_wallets(profile_id) values (target_profile_id) on conflict do nothing;
  select balance into wallet_balance from public.credit_wallets where profile_id = target_profile_id for update;
  if wallet_balance < credit_cost_value then raise exception 'Insufficient credit balance'; end if;

  expiry := now() + make_interval(days => requested_days);
  insert into public.static_residential_orders(profile_id, node_count, quota_bytes, price_per_gb_day, amount, credit_cost, expires_at)
  values (target_profile_id, 5, 5368709120, price_per_gb_day_value, total_usd, credit_cost_value, expiry)
  returning id into new_order_id;

  update public.credit_wallets set balance = balance - credit_cost_value, updated_at = now()
  where profile_id = target_profile_id returning balance into wallet_balance;
  insert into public.credit_ledger(profile_id, amount, balance_after, type, reference, note)
  values (target_profile_id, -credit_cost_value, wallet_balance, 'order_debit', 'static-residential:' || new_order_id::text,
    format('Static residential order #%s (5GB, %s days)', new_order_id, requested_days));

  for i in 1..5 loop
    select candidate.port into allocated_port from generate_series(10000, 20000) as candidate(port)
    where not exists (select 1 from public.static_residential_nodes where public_port = candidate.port)
    order by candidate.port limit 1;
    if allocated_port is null then raise exception 'No public static proxy port is available'; end if;
    insert into public.static_residential_nodes(order_id, upstream_proxy_id, public_port, service_name)
    values (new_order_id, selected_proxy_ids[i], allocated_port, 'static-residential-node-' || new_order_id::text || '-' || i::text);
    update public.static_residential_proxies set status = 'assigned', assigned_order_id = new_order_id, updated_at = now()
    where id = selected_proxy_ids[i];
  end loop;
  return new_order_id;
end;
$$;

revoke all on function public.create_static_residential_order(bigint, integer) from public, anon, authenticated;
grant execute on function public.create_static_residential_order(bigint, integer) to service_role;

create or replace function public.rotate_static_residential_node(target_node_id bigint)
returns table(node_id bigint, previous_proxy_id bigint, upstream_proxy_id bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  node_row public.static_residential_nodes%rowtype;
  order_row public.static_residential_orders%rowtype;
  replacement_proxy_id bigint;
begin
  select * into node_row from public.static_residential_nodes where id = target_node_id for update;
  if not found then raise exception 'Static residential node not found'; end if;
  select * into order_row from public.static_residential_orders where id = node_row.order_id for update;
  if order_row.status <> 'active' or order_row.expires_at <= now() then
    raise exception 'Static residential order is not active';
  end if;
  select id into replacement_proxy_id from public.static_residential_proxies
  where status = 'available' and id <> node_row.upstream_proxy_id
  order by id for update skip locked limit 1;
  if replacement_proxy_id is null then raise exception 'No spare static residential proxy is available for rotation'; end if;

  update public.static_residential_proxies set status = 'available', assigned_order_id = null, updated_at = now()
  where id = node_row.upstream_proxy_id;
  update public.static_residential_proxies set status = 'assigned', assigned_order_id = node_row.order_id, updated_at = now()
  where id = replacement_proxy_id;
  update public.static_residential_nodes
  set upstream_proxy_id = replacement_proxy_id, last_upstream_rotation_at = now(), next_upstream_rotation_at = now() + interval '1 hour', updated_at = now()
  where id = target_node_id;
  return query select target_node_id, node_row.upstream_proxy_id, replacement_proxy_id;
end;
$$;
revoke all on function public.rotate_static_residential_node(bigint) from public, anon, authenticated;
grant execute on function public.rotate_static_residential_node(bigint) to service_role;

create or replace function public.extend_static_residential_order(target_profile_id bigint, target_order_id bigint, requested_days integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.static_residential_orders%rowtype;
  credit_rate numeric;
  credit_cost_value numeric;
  wallet_balance numeric;
begin
  if requested_days not in (1, 3, 7, 15, 30) then raise exception 'Rental days must be one of: 1, 3, 7, 15, or 30'; end if;
  select * into order_row from public.static_residential_orders where id = target_order_id and profile_id = target_profile_id for update;
  if not found then raise exception 'Static residential order not found'; end if;
  if order_row.status in ('cancelled', 'suspended') then raise exception 'Static residential order cannot be extended'; end if;
  select coalesce((value #>> '{}')::numeric, 100) into credit_rate from public.app_settings where key = 'credits_per_usd';
  credit_cost_value := ceil(order_row.price_per_gb_day * 5 * requested_days * credit_rate * 100) / 100;
  insert into public.credit_wallets(profile_id) values (target_profile_id) on conflict do nothing;
  select balance into wallet_balance from public.credit_wallets where profile_id = target_profile_id for update;
  if wallet_balance < credit_cost_value then raise exception 'Insufficient credit balance'; end if;
  update public.credit_wallets set balance = balance - credit_cost_value, updated_at = now() where profile_id = target_profile_id returning balance into wallet_balance;
  update public.static_residential_orders set expires_at = greatest(expires_at, now()) + make_interval(days => requested_days), status = 'active', updated_at = now() where id = target_order_id;
  update public.static_residential_nodes set status = 'active', updated_at = now() where order_id = target_order_id;
  insert into public.credit_ledger(profile_id, amount, balance_after, type, reference, note)
  values (target_profile_id, -credit_cost_value, wallet_balance, 'order_extension_debit', 'static-residential:' || target_order_id::text,
    format('Static residential order #%s extended %s days', target_order_id, requested_days));
end;
$$;
revoke all on function public.extend_static_residential_order(bigint, bigint, integer) from public, anon, authenticated;
grant execute on function public.extend_static_residential_order(bigint, bigint, integer) to service_role;

alter table public.static_residential_proxies enable row level security;
alter table public.static_residential_orders enable row level security;
alter table public.static_residential_nodes enable row level security;
revoke all on public.static_residential_proxies, public.static_residential_orders, public.static_residential_nodes from anon, authenticated;
grant all on public.static_residential_proxies, public.static_residential_orders, public.static_residential_nodes to service_role;
