-- Runtime control-plane for dynamically provisioned proxy nodes.
-- Supabase is the durable source of truth; Nest SSE reads proxy_node_events.

alter table public.proxy_providers
  add column max_sandboxes integer check (max_sandboxes is null or max_sandboxes > 0),
  add column reserved_replacement_slots integer not null default 1 check (reserved_replacement_slots >= 0),
  add column max_concurrent_provisions integer not null default 2 check (max_concurrent_provisions > 0);

alter table public.provider_api_keys
  add column max_sandboxes integer check (max_sandboxes is null or max_sandboxes > 0);

create table public.proxy_nodes (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  provider_id bigint references public.proxy_providers(id) on delete set null,
  provider_api_key_id bigint references public.provider_api_keys(id) on delete set null,
  status text not null default 'queued' check (status in (
    'queued', 'provisioning', 'online', 'rotating', 'degraded', 'offline',
    'error', 'expired', 'terminating', 'terminated'
  )),
  public_host text,
  tunnel_port integer check (tunnel_port is null or tunnel_port between 1 and 65535),
  egress_ip inet,
  current_instance_id text,
  last_health_at timestamptz,
  last_status_change_at timestamptz not null default now(),
  next_rotation_at timestamptz,
  expires_at timestamptz,
  error_code text,
  error_message text,
  health jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.proxy_node_instances (
  id bigint generated by default as identity primary key,
  node_id bigint not null references public.proxy_nodes(id) on delete cascade,
  provider_id bigint not null references public.proxy_providers(id) on delete restrict,
  provider_api_key_id bigint references public.provider_api_keys(id) on delete set null,
  external_instance_id text not null,
  status text not null default 'provisioning' check (status in (
    'provisioning', 'running', 'stopping', 'stopped', 'error'
  )),
  started_at timestamptz,
  stopped_at timestamptz,
  expires_at timestamptz,
  last_heartbeat_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider_id, external_instance_id)
);

create table public.proxy_node_events (
  id bigint generated by default as identity primary key,
  node_id bigint not null references public.proxy_nodes(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index proxy_nodes_profile_status_idx on public.proxy_nodes(profile_id, status);
create index proxy_nodes_provider_status_idx on public.proxy_nodes(provider_id, status);
create index proxy_node_instances_node_created_idx on public.proxy_node_instances(node_id, created_at desc);
create index proxy_node_events_profile_id_idx on public.proxy_node_events(profile_id, id);

create trigger proxy_nodes_updated_at before update on public.proxy_nodes
for each row execute function public.set_updated_at();
create trigger proxy_node_instances_updated_at before update on public.proxy_node_instances
for each row execute function public.set_updated_at();

-- Preserve existing active resource-backed orders as runtime nodes. New worker
-- callbacks can progressively take ownership of these rows.
insert into public.proxy_nodes(
  order_id, profile_id, provider_id, status, public_host, tunnel_port, egress_ip,
  last_health_at, next_rotation_at, expires_at, metadata
)
select
  o.id,
  o.profile_id,
  r.provider_id,
  case when r.status = 'online' then 'online' else 'offline' end,
  nullif(r.secrets ->> 'host', ''),
  case when (r.secrets ->> 'port') ~ '^[0-9]+$' then (r.secrets ->> 'port')::integer else null end,
  case when coalesce(r.health ->> 'egressIp', '') <> '' then (r.health ->> 'egressIp')::inet else null end,
  case when r.status = 'online' then now() else null end,
  case
    when o.activated_at is not null then o.activated_at + interval '60 minutes'
    else null
  end,
  o.expires_at,
  jsonb_build_object('migratedFromResourceId', r.id)
from public.orders o
join public.resources r on r.id = o.resource_id
where o.status = 'active'
on conflict (order_id) do nothing;

-- Active orders automatically receive one logical node. Provisioning remains
-- asynchronous and moves queued -> provisioning -> online.
create or replace function public.ensure_proxy_node_for_active_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  resource_row public.resources%rowtype;
  new_node_id bigint;
begin
  if new.status = 'active' and old.status is distinct from new.status then
    if new.resource_id is not null then
      select * into resource_row from public.resources where id = new.resource_id;
    end if;

    insert into public.proxy_nodes(
      order_id, profile_id, provider_id, status, public_host, tunnel_port,
      next_rotation_at, expires_at, metadata
    ) values (
      new.id,
      new.profile_id,
      resource_row.provider_id,
      'queued',
      nullif(resource_row.secrets ->> 'host', ''),
      case when (resource_row.secrets ->> 'port') ~ '^[0-9]+$' then (resource_row.secrets ->> 'port')::integer else null end,
      coalesce(new.activated_at, now()) + interval '60 minutes',
      new.expires_at,
      case when new.resource_id is null then '{}'::jsonb else jsonb_build_object('resourceId', new.resource_id) end
    )
    on conflict (order_id) do update set
      expires_at = excluded.expires_at,
      updated_at = now()
    returning id into new_node_id;

    insert into public.proxy_node_events(node_id, profile_id, event_type, payload)
    values (new_node_id, new.profile_id, 'proxy.node.queued', jsonb_build_object('status', 'queued'));
  end if;
  return new;
end;
$$;

create trigger orders_create_proxy_node
after update of status on public.orders
for each row execute function public.ensure_proxy_node_for_active_order();

-- Worker-facing atomic update: status and its SSE event are committed together.
create or replace function public.report_proxy_node_status(
  target_node_id bigint,
  next_status text,
  reported_instance_id text default null,
  reported_egress_ip text default null,
  reported_public_host text default null,
  reported_tunnel_port integer default null,
  reported_next_rotation_at timestamptz default null,
  reported_health jsonb default '{}'::jsonb,
  reported_error_code text default null,
  reported_error_message text default null
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  target_node public.proxy_nodes%rowtype;
  new_event_id bigint;
begin
  if next_status not in (
    'queued', 'provisioning', 'online', 'rotating', 'degraded', 'offline',
    'error', 'expired', 'terminating', 'terminated'
  ) then raise exception 'Unsupported proxy node status'; end if;

  select * into target_node from public.proxy_nodes where id = target_node_id for update;
  if not found then raise exception 'Proxy node not found'; end if;

  update public.proxy_nodes set
    status = next_status,
    current_instance_id = coalesce(reported_instance_id, current_instance_id),
    egress_ip = case when reported_egress_ip is null then egress_ip else reported_egress_ip::inet end,
    public_host = coalesce(reported_public_host, public_host),
    tunnel_port = coalesce(reported_tunnel_port, tunnel_port),
    next_rotation_at = coalesce(reported_next_rotation_at, next_rotation_at),
    last_health_at = case when next_status in ('online', 'rotating') then now() else last_health_at end,
    last_status_change_at = case when status is distinct from next_status then now() else last_status_change_at end,
    health = coalesce(reported_health, '{}'::jsonb),
    error_code = reported_error_code,
    error_message = reported_error_message
  where id = target_node_id;

  insert into public.proxy_node_events(node_id, profile_id, event_type, payload)
  values (
    target_node_id,
    target_node.profile_id,
    'proxy.node.status',
    jsonb_strip_nulls(jsonb_build_object(
      'nodeId', target_node_id,
      'status', next_status,
      'instanceId', reported_instance_id,
      'egressIp', reported_egress_ip,
      'publicHost', reported_public_host,
      'tunnelPort', reported_tunnel_port,
      'nextRotationAt', reported_next_rotation_at,
      'errorCode', reported_error_code,
      'errorMessage', reported_error_message
    ))
  ) returning id into new_event_id;

  return new_event_id;
end;
$$;

alter table public.proxy_nodes enable row level security;
alter table public.proxy_node_instances enable row level security;
alter table public.proxy_node_events enable row level security;
revoke all on public.proxy_nodes, public.proxy_node_instances, public.proxy_node_events from anon, authenticated;
revoke all on function public.ensure_proxy_node_for_active_order() from public, anon, authenticated;
revoke all on function public.report_proxy_node_status(bigint, text, text, text, text, integer, timestamptz, jsonb, text, text) from public, anon, authenticated;
grant all on public.proxy_nodes, public.proxy_node_instances, public.proxy_node_events to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.report_proxy_node_status(bigint, text, text, text, text, integer, timestamptz, jsonb, text, text) to service_role;
