-- Durable order -> node provisioning pipeline.

alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check check (status in (
  'pending', 'provisioning', 'active', 'provisioning_failed',
  'expired', 'rejected', 'cancelled'
));

create table public.proxy_account_credentials (
  id bigint generated by default as identity primary key,
  profile_id bigint not null unique references public.profiles(id) on delete cascade,
  username text not null unique,
  password_ciphertext text not null,
  password_iv text not null,
  password_tag text not null,
  created_at timestamptz not null default now(),
  rotated_at timestamptz
);

create table public.proxy_provisioning_jobs (
  id bigint generated by default as identity primary key,
  node_id bigint not null references public.proxy_nodes(id) on delete cascade,
  action text not null default 'provision' check (action in ('provision', 'replace', 'terminate')),
  status text not null default 'queued' check (status in ('queued', 'running', 'retry', 'completed', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 5 check (max_attempts > 0),
  run_after timestamptz not null default now(),
  locked_by text,
  locked_until timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(node_id, action)
);

create table public.provider_capacity_leases (
  id uuid primary key default gen_random_uuid(),
  provider_id bigint not null references public.proxy_providers(id) on delete cascade,
  provider_api_key_id bigint not null references public.provider_api_keys(id) on delete cascade,
  node_id bigint not null references public.proxy_nodes(id) on delete cascade,
  purpose text not null default 'customer' check (purpose in ('customer', 'replacement')),
  status text not null default 'reserved' check (status in ('reserved', 'active', 'released')),
  leased_by text not null,
  lease_expires_at timestamptz not null,
  released_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index provider_capacity_live_node_idx
on public.provider_capacity_leases(node_id, purpose)
where released_at is null;
create index proxy_provisioning_jobs_claim_idx on public.proxy_provisioning_jobs(status, run_after, id);
create index provider_capacity_provider_live_idx on public.provider_capacity_leases(provider_id, lease_expires_at) where released_at is null;
create index provider_capacity_key_live_idx on public.provider_capacity_leases(provider_api_key_id, lease_expires_at) where released_at is null;

create trigger proxy_provisioning_jobs_updated_at before update on public.proxy_provisioning_jobs
for each row execute function public.set_updated_at();
create trigger provider_capacity_leases_updated_at before update on public.provider_capacity_leases
for each row execute function public.set_updated_at();

drop trigger if exists orders_create_proxy_node on public.orders;
drop function if exists public.ensure_proxy_node_for_active_order();

create or replace function public.transition_order(
  target_order_id bigint,
  next_status text,
  actor_profile_id bigint
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_order public.orders%rowtype;
  resource_row public.resources%rowtype;
  new_node_id bigint;
begin
  if next_status not in ('active', 'rejected') then raise exception 'Unsupported order transition'; end if;
  select * into current_order from public.orders where id = target_order_id for update;
  if not found then raise exception 'Order not found'; end if;
  if current_order.status <> 'pending' then raise exception 'Only pending orders can be reviewed'; end if;

  if next_status = 'active' then
    select * into resource_row from public.resources where id = current_order.resource_id;
    update public.orders set status = 'provisioning', activated_at = null, expires_at = null where id = target_order_id;

    insert into public.proxy_nodes(
      order_id, profile_id, provider_id, status, public_host, tunnel_port, expires_at, metadata
    ) values (
      current_order.id,
      current_order.profile_id,
      resource_row.provider_id,
      'queued',
      nullif(resource_row.secrets ->> 'host', ''),
      case when (resource_row.secrets ->> 'port') ~ '^[0-9]+$' then (resource_row.secrets ->> 'port')::integer else null end,
      null,
      jsonb_build_object('resourceId', current_order.resource_id)
    )
    on conflict (order_id) do update set status = 'queued', error_code = null, error_message = null, updated_at = now()
    returning id into new_node_id;

    insert into public.proxy_provisioning_jobs(node_id, action, status, run_after)
    values (new_node_id, 'provision', 'queued', now())
    on conflict (node_id, action) do update set status = 'queued', run_after = now(), last_error = null, updated_at = now();

    insert into public.proxy_node_events(node_id, profile_id, event_type, payload)
    values (new_node_id, current_order.profile_id, 'proxy.node.queued', jsonb_build_object('nodeId', new_node_id, 'status', 'queued'));
  else
    update public.orders set status = 'rejected' where id = target_order_id;
  end if;

  insert into public.activity_logs(actor_profile_id, event_type, entity_type, entity_id, description, tone)
  values (
    actor_profile_id,
    case when next_status = 'active' then 'order_approved_for_provisioning' else 'order_rejected' end,
    'order', target_order_id,
    case when next_status = 'active' then format('Order #%s was approved and queued for provisioning', target_order_id) else format('Order #%s was rejected', target_order_id) end,
    case when next_status = 'active' then 'success' else 'warning' end
  );
end;
$$;

create or replace function public.claim_proxy_provisioning_job(
  worker_id text,
  lock_seconds integer default 120
) returns setof public.proxy_provisioning_jobs
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed public.proxy_provisioning_jobs%rowtype;
begin
  update public.proxy_provisioning_jobs
  set status = 'retry', locked_by = null, locked_until = null, run_after = now(), last_error = coalesce(last_error, 'Worker lease expired')
  where status = 'running' and locked_until < now();

  select * into claimed
  from public.proxy_provisioning_jobs
  where status in ('queued', 'retry') and run_after <= now() and attempts < max_attempts
  order by run_after, id
  for update skip locked
  limit 1;

  if not found then return; end if;
  update public.proxy_provisioning_jobs
  set status = 'running', attempts = attempts + 1, locked_by = worker_id,
      locked_until = now() + make_interval(secs => greatest(30, lock_seconds))
  where id = claimed.id
  returning * into claimed;
  return next claimed;
end;
$$;

create or replace function public.reserve_provider_capacity(
  target_node_id bigint,
  worker_id text,
  lease_seconds integer default 300,
  target_purpose text default 'customer'
) returns table(lease_id uuid, selected_provider_id bigint, selected_api_key_id bigint, provider_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  provider_row public.proxy_providers%rowtype;
  key_row public.provider_api_keys%rowtype;
  provider_used integer;
  provider_limit integer;
  key_used integer;
begin
  if target_purpose not in ('customer', 'replacement') then raise exception 'Unsupported capacity purpose'; end if;
  update public.provider_capacity_leases set status = 'released', released_at = now()
  where released_at is null and lease_expires_at < now();

  return query
  select l.id, l.provider_id, l.provider_api_key_id, p.code
  from public.provider_capacity_leases l join public.proxy_providers p on p.id = l.provider_id
  where l.node_id = target_node_id and l.purpose = target_purpose and l.released_at is null
  limit 1;
  if found then return; end if;

  for provider_row in
    select p.* from public.proxy_providers p
    where p.status = 'active'
    order by coalesce((p.metadata ->> 'priority')::integer, 100), p.id
    for update skip locked
  loop
    select count(*) into provider_used from public.provider_capacity_leases
    where provider_id = provider_row.id and released_at is null and lease_expires_at >= now();
    provider_limit := provider_row.max_sandboxes;
    if provider_limit is not null and target_purpose = 'customer' then
      provider_limit := greatest(0, provider_limit - provider_row.reserved_replacement_slots);
    end if;
    if provider_limit is not null and provider_used >= provider_limit then continue; end if;

    select k.* into key_row
    from public.provider_api_keys k
    where k.provider_id = provider_row.id and k.status = 'active'
      and (
        k.max_sandboxes is null or
        (select count(*) from public.provider_capacity_leases l where l.provider_api_key_id = k.id and l.released_at is null and l.lease_expires_at >= now()) < k.max_sandboxes
      )
    order by k.created_at, k.id
    for update skip locked
    limit 1;
    if not found then continue; end if;

    insert into public.provider_capacity_leases(provider_id, provider_api_key_id, node_id, purpose, leased_by, lease_expires_at)
    values (provider_row.id, key_row.id, target_node_id, target_purpose, worker_id, now() + make_interval(secs => greatest(60, lease_seconds)))
    returning id into lease_id;
    selected_provider_id := provider_row.id;
    selected_api_key_id := key_row.id;
    provider_code := provider_row.code;
    return next;
    return;
  end loop;
end;
$$;

create or replace function public.complete_proxy_provisioning(
  target_job_id bigint,
  worker_id text,
  external_instance_id text,
  reported_egress_ip text,
  reported_public_host text,
  reported_tunnel_port integer,
  reported_next_rotation_at timestamptz
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  job_row public.proxy_provisioning_jobs%rowtype;
  node_row public.proxy_nodes%rowtype;
  order_row public.orders%rowtype;
  now_at timestamptz := now();
begin
  select * into job_row from public.proxy_provisioning_jobs where id = target_job_id for update;
  if not found or job_row.status <> 'running' or job_row.locked_by <> worker_id then raise exception 'Provisioning job lease is not owned by worker'; end if;
  select * into node_row from public.proxy_nodes where id = job_row.node_id for update;
  select * into order_row from public.orders where id = node_row.order_id for update;

  update public.proxy_nodes set status = 'online', current_instance_id = external_instance_id,
    egress_ip = nullif(reported_egress_ip, '')::inet, public_host = reported_public_host,
    tunnel_port = reported_tunnel_port, last_health_at = now_at, last_status_change_at = now_at,
    next_rotation_at = reported_next_rotation_at, expires_at = now_at + make_interval(days => order_row.rental_days),
    error_code = null, error_message = null, health = jsonb_build_object('reachable', true, 'checkedAt', now_at)
  where id = node_row.id;

  update public.orders set status = 'active', activated_at = now_at,
    expires_at = now_at + make_interval(days => order_row.rental_days)
  where id = order_row.id;
  update public.proxy_provisioning_jobs set status = 'completed', locked_until = null where id = target_job_id;
  update public.provider_capacity_leases set status = 'active', lease_expires_at = now_at + make_interval(days => order_row.rental_days)
  where node_id = node_row.id and released_at is null;
  insert into public.proxy_node_events(node_id, profile_id, event_type, payload)
  values (node_row.id, node_row.profile_id, 'proxy.node.status', jsonb_build_object('nodeId', node_row.id, 'status', 'online', 'egressIp', reported_egress_ip, 'nextRotationAt', reported_next_rotation_at));
end;
$$;

create or replace function public.fail_proxy_provisioning(
  target_job_id bigint,
  worker_id text,
  failure_message text,
  retry_delay_seconds integer default 30
) returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  job_row public.proxy_provisioning_jobs%rowtype;
  node_row public.proxy_nodes%rowtype;
  next_job_status text;
begin
  select * into job_row from public.proxy_provisioning_jobs where id = target_job_id for update;
  if not found or job_row.status <> 'running' or job_row.locked_by <> worker_id then raise exception 'Provisioning job lease is not owned by worker'; end if;
  select * into node_row from public.proxy_nodes where id = job_row.node_id for update;
  next_job_status := case when job_row.attempts >= job_row.max_attempts then 'failed' else 'retry' end;
  update public.proxy_provisioning_jobs set status = next_job_status, last_error = left(failure_message, 2000),
    locked_by = null, locked_until = null,
    run_after = case when next_job_status = 'retry' then now() + make_interval(secs => greatest(5, retry_delay_seconds)) else run_after end
  where id = target_job_id;
  update public.proxy_nodes set status = case when next_job_status = 'failed' then 'error' else 'queued' end,
    error_code = 'provisioning_failed', error_message = left(failure_message, 2000), last_status_change_at = now()
  where id = node_row.id;
  if next_job_status = 'failed' then update public.orders set status = 'provisioning_failed' where id = node_row.order_id; end if;
  update public.provider_capacity_leases set status = 'released', released_at = now() where node_id = node_row.id and released_at is null;
  insert into public.proxy_node_events(node_id, profile_id, event_type, payload)
  values (node_row.id, node_row.profile_id, 'proxy.node.status', jsonb_build_object('nodeId', node_row.id, 'status', case when next_job_status = 'failed' then 'error' else 'queued' end, 'errorMessage', left(failure_message, 2000)));
  return next_job_status;
end;
$$;

alter table public.proxy_account_credentials enable row level security;
alter table public.proxy_provisioning_jobs enable row level security;
alter table public.provider_capacity_leases enable row level security;
revoke all on public.proxy_account_credentials, public.proxy_provisioning_jobs, public.provider_capacity_leases from anon, authenticated;
grant all on public.proxy_account_credentials, public.proxy_provisioning_jobs, public.provider_capacity_leases to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.claim_proxy_provisioning_job(text, integer) from public, anon, authenticated;
revoke all on function public.reserve_provider_capacity(bigint, text, integer, text) from public, anon, authenticated;
revoke all on function public.complete_proxy_provisioning(bigint, text, text, text, text, integer, timestamptz) from public, anon, authenticated;
revoke all on function public.fail_proxy_provisioning(bigint, text, text, integer) from public, anon, authenticated;
grant execute on function public.claim_proxy_provisioning_job(text, integer) to service_role;
grant execute on function public.reserve_provider_capacity(bigint, text, integer, text) to service_role;
grant execute on function public.complete_proxy_provisioning(bigint, text, text, text, text, integer, timestamptz) to service_role;
grant execute on function public.fail_proxy_provisioning(bigint, text, text, integer) to service_role;
