-- Dedicated egress gateways belong to a Blaxel account/workspace. Store them
-- against the encrypted provider API-key record, never in application env.
create table if not exists public.blaxel_egress_gateways (
  id bigint generated by default as identity primary key,
  provider_api_key_id bigint not null references public.provider_api_keys(id) on delete restrict,
  name text not null check (name ~ '^[A-Za-z0-9][A-Za-z0-9-]{0,126}$'),
  region text not null check (region ~ '^[a-z]{2}-[a-z]+-[0-9]+$'),
  status text not null default 'active' check (status in ('active', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider_api_key_id, name)
);

alter table public.blaxel_egress_gateway_leases
  add column if not exists gateway_id bigint references public.blaxel_egress_gateways(id) on delete restrict;

-- Migrate live leases created by the earlier environment-based pool. This
-- preserves currently-running nodes, so a deployment cannot reassign their IP.
insert into public.blaxel_egress_gateways(provider_api_key_id, name, region)
select n.provider_api_key_id, l.gateway, l.region
from public.blaxel_egress_gateway_leases l
join public.proxy_nodes n on n.id = l.node_id
join public.provider_api_keys k on k.id = n.provider_api_key_id
join public.proxy_providers p on p.id = k.provider_id and p.code = 'blaxel'
where l.gateway is not null and l.region is not null and n.provider_api_key_id is not null
on conflict (provider_api_key_id, name) do nothing;

update public.blaxel_egress_gateway_leases l
set gateway_id = g.id
from public.proxy_nodes n, public.blaxel_egress_gateways g
where n.id = l.node_id
  and g.provider_api_key_id = n.provider_api_key_id
  and g.name = l.gateway
  and l.gateway_id is null;

delete from public.blaxel_egress_gateway_leases
where gateway_id is null or (status = 'reserved' and lease_expires_at < now());
alter table public.blaxel_egress_gateway_leases alter column gateway drop not null;
alter table public.blaxel_egress_gateway_leases drop constraint if exists blaxel_egress_gateway_leases_gateway_key;
create unique index if not exists blaxel_egress_gateway_leases_gateway_id_unique
  on public.blaxel_egress_gateway_leases(gateway_id) where gateway_id is not null;

create or replace function public.reserve_blaxel_egress_gateway(
  target_node_id bigint,
  target_provider_api_key_id bigint,
  lease_seconds integer default 900
) returns table(selected_region text, selected_gateway text)
language plpgsql security definer set search_path = public as $$
declare selected public.blaxel_egress_gateways%rowtype;
begin
  if target_node_id is null or target_provider_api_key_id is null then
    raise exception 'Invalid Blaxel egress gateway reservation request';
  end if;
  if not exists (
    select 1 from public.provider_api_keys k
    join public.proxy_providers p on p.id = k.provider_id
    where k.id = target_provider_api_key_id and p.code = 'blaxel' and k.status = 'active'
  ) then
    raise exception 'Blaxel provider API key is not active';
  end if;

  perform pg_advisory_xact_lock(hashtext('nodenesia:blaxel-egress-gateway-pool'));
  delete from public.blaxel_egress_gateway_leases
    where status = 'reserved' and lease_expires_at < now();
  -- Replacement reaches allocation after its old sandbox has been terminated.
  delete from public.blaxel_egress_gateway_leases where node_id = target_node_id;

  select g.* into selected
  from public.blaxel_egress_gateways g
  where g.provider_api_key_id = target_provider_api_key_id
    and g.status = 'active'
    and not exists (
      select 1 from public.blaxel_egress_gateway_leases l where l.gateway_id = g.id
    )
  order by random()
  limit 1;

  if not found then return; end if;
  insert into public.blaxel_egress_gateway_leases(node_id, gateway_id, gateway, region, status, lease_expires_at)
  values (
    target_node_id, selected.id, selected.name, selected.region, 'reserved',
    now() + make_interval(secs => greatest(60, least(3600, lease_seconds)))
  );
  return query select selected.region, selected.name;
end;
$$;

alter table public.blaxel_egress_gateways enable row level security;
revoke all on public.blaxel_egress_gateways from public, anon, authenticated;
revoke all on function public.reserve_blaxel_egress_gateway(bigint, bigint, integer) from public, anon, authenticated;
grant all on public.blaxel_egress_gateways to service_role;
grant execute on function public.reserve_blaxel_egress_gateway(bigint, bigint, integer) to service_role;
