-- Modular admin data: proxy providers, encrypted provider credentials and general settings.
create table public.proxy_providers (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  api_base_url text,
  status text not null default 'active' check (status in ('active', 'disabled')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.provider_api_keys (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.proxy_providers(id) on delete cascade,
  label text not null,
  key_prefix text not null,
  key_last4 text not null,
  secret_ciphertext text not null,
  secret_iv text not null,
  secret_tag text not null,
  status text not null default 'active' check (status in ('active', 'revoked')),
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.resources
  add column provider_id bigint references public.proxy_providers(id) on delete set null;

create index provider_api_keys_provider_status_idx on public.provider_api_keys(provider_id, status);
create index resources_provider_idx on public.resources(provider_id);

create trigger proxy_providers_updated_at before update on public.proxy_providers
for each row execute function public.set_updated_at();
create trigger app_settings_updated_at before update on public.app_settings
for each row execute function public.set_updated_at();

insert into public.proxy_providers(code, name, api_base_url, metadata)
values ('e2b', 'E2B', 'https://api.e2b.app', '{"driver":"e2b"}'::jsonb)
on conflict (code) do nothing;

update public.resources
set provider_id = (select id from public.proxy_providers where code = 'e2b')
where provider_id is null;

insert into public.app_settings(key, value) values
  ('site_name', '"Proxy Node"'::jsonb),
  ('support_email', '""'::jsonb),
  ('default_currency', '"USD"'::jsonb)
on conflict (key) do nothing;

alter table public.proxy_providers enable row level security;
alter table public.provider_api_keys enable row level security;
alter table public.app_settings enable row level security;
revoke all on public.proxy_providers, public.provider_api_keys, public.app_settings from anon, authenticated;
grant all on public.proxy_providers, public.provider_api_keys, public.app_settings to service_role;
grant usage, select on all sequences in schema public to service_role;
