-- Extensible service catalog. SOCKS5 is the first product, not the schema itself.
create table public.products (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  service_type text not null,
  description text not null default '',
  is_active boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null default 'client' check (role in ('admin', 'client')),
  status text not null default 'active' check (status in ('active', 'suspended')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.plans (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  code text not null,
  name text not null,
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  currency char(3) not null default 'USD',
  duration_hours integer not null check (duration_hours > 0),
  rotation_minutes integer not null default 60 check (rotation_minutes > 0),
  highlighted boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(product_id, code)
);

create table public.resources (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  code text not null unique,
  name text not null,
  status text not null default 'offline' check (status in ('online', 'offline', 'maintenance')),
  is_public boolean not null default true,
  region jsonb not null default '{}'::jsonb,
  capabilities jsonb not null default '{}'::jsonb,
  health jsonb not null default '{}'::jsonb,
  -- Server-only credentials. Never return this column from a public catalog endpoint.
  secrets jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete restrict,
  plan_id bigint not null references public.plans(id) on delete restrict,
  resource_id bigint not null references public.resources(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending', 'active', 'expired', 'rejected', 'cancelled')),
  payment_method text not null check (payment_method in ('bank_transfer', 'crypto')),
  payment_reference text,
  amount numeric(12,2) not null check (amount >= 0),
  currency char(3) not null default 'USD',
  plan_name_snapshot text not null,
  resource_name_snapshot text not null,
  activated_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.api_keys (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  label text not null,
  prefix text not null,
  key_hash text not null unique,
  status text not null default 'active' check (status in ('active', 'revoked')),
  request_count bigint not null default 0,
  last_used_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.usage_daily (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  resource_id bigint not null references public.resources(id) on delete cascade,
  usage_date date not null default current_date,
  requests bigint not null default 0 check (requests >= 0),
  successful_requests bigint not null default 0 check (successful_requests >= 0),
  bytes_transferred bigint not null default 0 check (bytes_transferred >= 0),
  unique(profile_id, resource_id, usage_date)
);

create table public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_profile_id bigint references public.profiles(id) on delete set null,
  event_type text not null,
  entity_type text,
  entity_id bigint,
  description text not null,
  tone text not null default 'neutral' check (tone in ('success', 'warning', 'neutral')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index orders_profile_created_idx on public.orders(profile_id, created_at desc);
create index orders_status_created_idx on public.orders(status, created_at desc);
create index resources_product_status_idx on public.resources(product_id, status);
create index usage_daily_profile_date_idx on public.usage_daily(profile_id, usage_date desc);
create index activity_logs_created_idx on public.activity_logs(created_at desc);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger products_updated_at before update on public.products for each row execute function public.set_updated_at();
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger plans_updated_at before update on public.plans for each row execute function public.set_updated_at();
create trigger resources_updated_at before update on public.resources for each row execute function public.set_updated_at();
create trigger orders_updated_at before update on public.orders for each row execute function public.set_updated_at();

-- Email/password sign-ups in Supabase Auth receive an application profile.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(auth_user_id, email, name)
  values (
    new.id,
    lower(new.email),
    coalesce(nullif(new.raw_user_meta_data ->> 'name', ''), split_part(new.email, '@', 1))
  )
  on conflict (email) do update
    set auth_user_id = excluded.auth_user_id,
        name = excluded.name,
        updated_at = now();
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

revoke all on function public.handle_new_auth_user() from public, anon, authenticated;

-- Keeps approval/rejection atomic and prevents double approval under concurrency.
create or replace function public.transition_order(
  target_order_id bigint,
  next_status text,
  actor_profile_id bigint
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_order public.orders%rowtype;
  plan_duration integer;
begin
  if next_status not in ('active', 'rejected') then
    raise exception 'Unsupported order transition';
  end if;

  select * into current_order from public.orders where id = target_order_id for update;
  if not found then raise exception 'Order not found'; end if;
  if current_order.status <> 'pending' then raise exception 'Only pending orders can be reviewed'; end if;

  if next_status = 'active' then
    select duration_hours into plan_duration from public.plans where id = current_order.plan_id;
    update public.orders
      set status = 'active', activated_at = now(), expires_at = now() + make_interval(hours => plan_duration)
      where id = target_order_id;
  else
    update public.orders set status = 'rejected' where id = target_order_id;
  end if;

  insert into public.activity_logs(actor_profile_id, event_type, entity_type, entity_id, description, tone)
  values (
    actor_profile_id,
    case when next_status = 'active' then 'order_approved' else 'order_rejected' end,
    'order', target_order_id,
    format('Order #%s was %s', target_order_id, next_status),
    case when next_status = 'active' then 'success' else 'warning' end
  );
end;
$$;

-- Nest is the sole data gateway. Secret/server key retains service_role access.
alter table public.products enable row level security;
alter table public.profiles enable row level security;
alter table public.plans enable row level security;
alter table public.resources enable row level security;
alter table public.orders enable row level security;
alter table public.api_keys enable row level security;
alter table public.usage_daily enable row level security;
alter table public.activity_logs enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on function public.transition_order(bigint, text, bigint) from public, anon, authenticated;
grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.transition_order(bigint, text, bigint) to service_role;
