-- Admin-managed catalog for services and digital goods such as accounts, keys and files.
create table public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
  add column category_id bigint references public.categories(id) on delete restrict,
  add column sku text unique,
  add column product_kind text not null default 'service'
    check (product_kind in ('account', 'digital', 'service', 'other')),
  add column fulfillment_type text not null default 'manual'
    check (fulfillment_type in ('automatic', 'manual', 'service')),
  add column base_price numeric(12,2) not null default 0 check (base_price >= 0),
  add column currency char(3) not null default 'USD',
  add column stock_quantity integer check (stock_quantity is null or stock_quantity >= 0),
  add column image_url text,
  add column is_featured boolean not null default false;

create index products_category_active_idx on public.products(category_id, is_active);
create index categories_active_sort_idx on public.categories(is_active, sort_order);

create trigger categories_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

insert into public.categories(slug, name, description, sort_order)
values ('services', 'Services', 'Hosted services and subscriptions', 10)
on conflict (slug) do update set name = excluded.name, description = excluded.description;

update public.products
set category_id = (select id from public.categories where slug = 'services'),
    sku = coalesce(sku, upper(code)),
    product_kind = 'service',
    fulfillment_type = 'service'
where category_id is null;

alter table public.categories enable row level security;
revoke all on public.categories from anon, authenticated;
grant all on public.categories to service_role;
grant usage, select on all sequences in schema public to service_role;
